title: "Sausage Culture in the Austrian Alps"
description: "A delicious journey through alpine sausage traditions, festivals, and heritage recipes."
theme: jekyll-theme-cayman

# Customize theme colors and visuals for a sausage-inspired look
# (These variables depend on the theme's support)

sass:
  style: compressed

# Example of custom color palette if the theme supports it
# These are conceptual and may require additional CSS overrides
colors:
  background: "#fff8f0"     # Sausage casing beige
  text: "#5e3c1c"           # Smoked meat brown
  accent: "#a83232"         # Paprika red
  link: "#8b0000"            # Deep sausage red
  border: "#d3b89b"          # Natural twine tan

logo: "/images/sausage-logo.png"
favicon: "/images/sausage-favicon.ico"

collections:
  recipes:
    output: true
  interviews:
    output: true
  festivals:
    output: true

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "Sausage Varieties"
    url: "/docs/sausages.html"
  - title: "Recipes"
    url: "/recipes/"
  - title: "Festivals"
    url: "/docs/festivals.html"
  - title: "Gallery"
    url: "/images/"
  - title: "Contribute"
    url: "/docs/contributing.html"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
